CREATE TABLE `velocafe`.`PRODUITS` (
  `ID_PRODUIT` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `MONTANT_HT` DOUBLE NULL COMMENT '',
  `MONTANT_TVA` DOUBLE NULL COMMENT '',
  `DATE_CRE` DATE NULL COMMENT '',
  `USER_CRE` VARCHAR(20) NULL COMMENT '',
  `TITRE` VARCHAR(150) NULL COMMENT '',
  `REF_PRODUIT` VARCHAR(45) NULL COMMENT '',
  `CATEGORIE` VARCHAR(10) NULL COMMENT '',
  `SOUS_CATEGORIE` VARCHAR(10) NULL COMMENT '',
  `ETAT` VARCHAR(1) NULL COMMENT '',
  `REF_TECHNIQUE` VARCHAR(45) NULL COMMENT '',
  `DATE_FAB` DATE NULL COMMENT '',
  `TYP_USAGE` VARCHAR(3) NULL COMMENT '',
  `DIAM_ROUE` VARCHAR(5) NULL COMMENT '',
  `TAILL_CADRE` VARCHAR(4) NULL COMMENT '',
  `DIM_CADRE` INT NULL COMMENT '',
  `DISPO` VARCHAR(5) NULL COMMENT '',
  PRIMARY KEY (`ID_PRODUIT`)  COMMENT '');
  
  CREATE TABLE `img` (
  `ID_IMG` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PRODUIT` varchar(45) DEFAULT NULL,
  `IMG` longblob,
  `MIME_TYPE` varchar(45) DEFAULT NULL,
  `FILE_NAME` varchar(80) DEFAULT NULL,
  `ORDRE` int(11) DEFAULT NULL,
  `DATE_CRE` date DEFAULT NULL,
  `USER_CRE` varchar(20) DEFAULT NULL,
  `SIZE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID_IMG`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

ALTER TABLE `velocafe`.`produits` 
ADD COLUMN `USER_SIZE` INT NULL COMMENT '' AFTER `DISPO`,
ADD COLUMN `STYLE` VARCHAR(10) NULL COMMENT '' AFTER `USER_SIZE`,
ADD COLUMN `OPTION_1` VARCHAR(10) NULL COMMENT '' AFTER `STYLE`,
ADD COLUMN `OPTION_2` VARCHAR(10) NULL COMMENT '' AFTER `OPTION_1`,
ADD COLUMN `OPTION_3` VARCHAR(10) NULL COMMENT '' AFTER `OPTION_2`;

ALTER TABLE `velocafe`.`produits` 
ADD COLUMN `SIZE_CAT` VARCHAR(10) NULL COMMENT '' AFTER `OPTION_3`,
ADD COLUMN `WEIGHT_CAT` VARCHAR(10) NULL COMMENT '' AFTER `SIZE_CAT`,
ADD COLUMN `PACK_CAT` VARCHAR(10) NULL COMMENT '' AFTER `WEIGHT_CAT`,
ADD COLUMN `STOCK_OPTION` VARCHAR(10) NULL COMMENT '' AFTER `PACK_CAT`,
ADD COLUMN `COLOR` VARCHAR(10) NULL COMMENT '' AFTER `STOCK_OPTION`,
ADD COLUMN `SUSP_SEAT` VARCHAR(1) NULL COMMENT '' AFTER `COLOR`,
ADD COLUMN `EASY_ENTRY` VARCHAR(1) NULL COMMENT '' AFTER `SUSP_SEAT`;

CREATE TABLE VELOCAFE.USER(USERNAME VARCHAR(64) PRIMARY KEY, PASSWORD VARCHAR(64));
CREATE TABLE VELOCAFE.USERROLES(USERNAME VARCHAR(64), USERROLES VARCHAR(32));

ALTER TABLE `velocafe`.`user` 
ADD COLUMN `NAME` VARCHAR(100) NULL COMMENT '' AFTER `PASSWORD`,
ADD COLUMN `SURNAME` VARCHAR(100) NULL COMMENT '' AFTER `NAME`,
ADD COLUMN `PREFIX` VARCHAR(10) NULL COMMENT '' AFTER `SURNAME`,
ADD COLUMN `BIRTHDATE` DATE NULL COMMENT '' AFTER `PREFIX`,
ADD COLUMN `FIXE` VARCHAR(45) NULL COMMENT '' AFTER `BIRTHDATE`,
ADD COLUMN `MOBILE` VARCHAR(45) NULL COMMENT '' AFTER `FIXE`,
ADD COLUMN `BUREAU` VARCHAR(45) NULL COMMENT '' AFTER `MOBILE`,
ADD COLUMN `ADRESSE1` VARCHAR(100) NULL COMMENT '' AFTER `BUREAU`,
ADD COLUMN `ADRESSE2` VARCHAR(100) NULL COMMENT '' AFTER `ADRESSE1`,
ADD COLUMN `ADRESSE3` VARCHAR(100) NULL COMMENT '' AFTER `ADRESSE2`,
ADD COLUMN `COMPLEMENT` VARCHAR(150) NULL COMMENT '' AFTER `ADRESSE3`,
ADD COLUMN `CP` VARCHAR(45) NULL COMMENT '' AFTER `COMPLEMENT`,
ADD COLUMN `VILLE` VARCHAR(100) NULL COMMENT '' AFTER `CP`;

ALTER TABLE `velocafe`.`user` 
ADD COLUMN `PAYS` VARCHAR(10) NULL COMMENT '' AFTER `VILLE`;

ALTER TABLE `velocafe`.`produits` 
ADD COLUMN `MARQUE` VARCHAR(100) NULL COMMENT '' AFTER `EASY_ENTRY`;

ALTER TABLE `velocafe`.`produits` 
CHANGE COLUMN `DIM_CADRE` `DIM_CADRE` VARCHAR(15) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN `USER_SIZE` `USER_SIZE` VARCHAR(15) NULL DEFAULT NULL COMMENT '' ;
